# Generated by Django 5.2.1 on 2025-05-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('XXS', 'Double Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='M', max_length=3)),
                ('color', models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('black', 'Black'), ('grey', 'Grey')], default='white', max_length=10)),
                ('image', models.ImageField(upload_to='cars/')),
                ('category', models.CharField(choices=[('t', 'T-shirt'), ('h', 'Hoodies')], default='t', max_length=10)),
            ],
        ),
    ]
